// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtzkfO2x5A5Glfu-A04qrnNX1MMRnfsPA',
    appId: '1:212492569517:web:5e9e63d39f9100b25e2f24',
    messagingSenderId: '212492569517',
    projectId: 'zh-transport-bus',
    authDomain: 'zh-transport-bus.firebaseapp.com',
    databaseURL: 'https://zh-transport-bus-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zh-transport-bus.appspot.com',
    measurementId: 'G-8WE00BP6KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSXAKBLLpVp8R2tjYkq4z09gohKBge1ac',
    appId: '1:212492569517:android:a5102ec31ebef8635e2f24',
    messagingSenderId: '212492569517',
    projectId: 'zh-transport-bus',
    databaseURL: 'https://zh-transport-bus-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zh-transport-bus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWEoag8panZieMBkQQqHuEcnB8ByyrOcA',
    appId: '1:212492569517:ios:a0ad464e939e3fe95e2f24',
    messagingSenderId: '212492569517',
    projectId: 'zh-transport-bus',
    databaseURL: 'https://zh-transport-bus-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zh-transport-bus.appspot.com',
    iosClientId: '212492569517-1q8295nl6n574g34dtfss65qg9bra9pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.bus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWEoag8panZieMBkQQqHuEcnB8ByyrOcA',
    appId: '1:212492569517:ios:a0ad464e939e3fe95e2f24',
    messagingSenderId: '212492569517',
    projectId: 'zh-transport-bus',
    databaseURL: 'https://zh-transport-bus-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zh-transport-bus.appspot.com',
    iosClientId: '212492569517-1q8295nl6n574g34dtfss65qg9bra9pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.bus',
  );
}
